### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by patro999** [genomanetwork/GEN#5]
https://genoma.network/ shows only Nginx welcome screen

**Comment by genomanetwork** [comment]
> https://genoma.network/ shows only Nginx welcome screen

Hi! Yes, project is still under development. Now we are creating a new official site only for **Gen of Liberty**, where we will keep all the information about the currency and our blockchain updated. [Gen of Liberty](https://genofliberty.com/)

About **Genoma Network**, soon we will upload a _"Coming soon"_ site announcing the project progress, but we estimate its launch by the end of this year _(late 2021)_.

Thanks for writing to us!
Best Regards

**Comment by genomanetwork** [comment]
Hi @patro999 
May I close this ticket?

**Comment by patro999** [comment]
Sure ;)
